On-Premises Quick-start improvements
cksource/ckeditor-cs-on-premises-infrastructure pull request #7
Opened 2021-06-09 13:11 UTC by LukaszGudel

This PR includes a collection of small fixes and improvements to On-Premises Quick-start. 

@godai78 Could you review the whole README files and other files containing messages, steps and errors? List of those files:
- README.md
- quick-start/README.md
- quick-start/utils/steps.json
- quick-start/utils/errors.json
- Lines 75-78 in quick-start/setup.js

2021-06-10 16:25 UTC, godai78 requested changes

2021-06-10 16:25 UTC, godai78 commented on README.md
> +Collaboration Server On-Premises Quick-Start allows you to quickly set up the infrastructure needed to use CKEditor 5 with Real-Time Collaboration and Collaboration Server On-Premises. After running
```suggestion
The Collaboration Server On-Premises Quick-Start guide lets you to quickly set up the infrastructure needed to use CKEditor 5 with Real-Time Collaboration and Collaboration Server On-Premises. After running a single setup command you can run a working CKEditor 5 instance and start testing our solution, with the Collaboration Server running locally, on your machine. Check out the [On-Premises Quick-start](/quick-start) guide.
```

2021-06-10 16:25 UTC, godai78 commented on quick-start/README.md
> +On-Premises Quick-Start installation will download few docker images with about 2GB in size. Similar space on your disk is also required.
```suggestion
The On-Premises Quick-Start installation will download a few docker images about 2GB in size. Similar free space on your disk is hence required.
```

2021-06-10 16:25 UTC, godai78 commented on quick-start/README.md
> +2. Verify if you have all needed tools installed by running this command in your terminal:
```suggestion
2. Verify if you have all necessary tools installed by running this command in your terminal:
```

2021-06-10 16:25 UTC, godai78 commented on quick-start/README.md
> +4. Run On-Premises Quick-Start, replacing credentials placeholders with your credentials:
```suggestion
4. Run On-Premises Quick-Start, replacing the credentials placeholders with your own credentials:
```

2021-06-10 16:25 UTC, godai78 commented on quick-start/README.md
> +**Running this setup process for the first time may take several minutes.** It has to pull few docker images from the web, install packages and build the editor bundle. Further command runs will be m
```suggestion
**Running this setup process for the first time may take several minutes.** It has to pull a few docker images from the web, install the packages and build the editor bundle. The following command runs will be much shorter. After the successful installation, you should see a message `Visit http://localhost:3000 to start collaborating`. Open this page in your browser. 
```

2021-06-10 16:25 UTC, godai78 commented on quick-start/README.md
> +Only 3 arguments are needed to successfully run our On-Premises Quick-Start. There are other optional arguments to customize this setup process. Here is a list of all possible arguments:
```suggestion
Only 3 arguments are needed to successfully run our On-Premises Quick-Start. There are also other optional arguments to customize this setup process. Here is a list of all possible arguments:
```

2021-06-10 16:25 UTC, godai78 commented on quick-start/README.md
> +**Note:** If you use different ports, then please remember to update URL endpoints after opening a sample page.
```suggestion
**Note:** If you use different ports than the default ones, please remember to update URL endpoints after opening a sample page.
```

2021-06-11 07:33 UTC, godai78 approved these changes

2021-06-14 13:20 UTC, SlawekGreczyn approved these changes

2021-06-23 07:53 UTC, merged